version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ecommerce_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - ecommerce-network
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: ecommerce_redis
    ports:
      - "6379:6379"
    networks:
      - ecommerce-network

  zookeeper:
    container_name: ecommerce_zookeeper
    image: bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - ecommerce-network

  kafka:
    container_name: ecommerce_kafka
    image: bitnami/kafka:latest
    environment:
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_ZOOKEEPER_CONNECT=ecommerce_zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - ecommerce-network

volumes:
  mysql_data: {}
  zookeeper_data: {}

networks: 
  ecommerce-network:
